version = 1

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true